stages:
  - test

rubocop:
  stage: test
  image: ruby:2.4.1
  script:
    - gem install rubocop -v 0.49.1
    - rubocop -F

rspec:
  stage: test
  image: ruby:2.4.1
  script:
    - bundle install
    - bundle exec rspec --fail-fast -f progress
