# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: expedia 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "expedia".freeze
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Alistair A. Israel".freeze]
  s.date = "2017-09-14"
  s.description = "TODO: longer description of your gem".freeze
  s.email = "aisrael@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "features/expedia.feature",
    "features/step_definitions/expedia_steps.rb",
    "features/support/env.rb",
    "lib/expedia.rb",
    "spec/spec_helper.rb",
    "test.rb"
  ]
  s.homepage = "http://github.com/aisrael/expedia".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.12".freeze
  s.summary = "TODO: one-line summary of your gem".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>.freeze, ["~> 5.0"])
      s.add_runtime_dependency(%q<faraday>.freeze, ["~> 0.9.2"])
      s.add_runtime_dependency(%q<json>.freeze, ["~> 2.1.0"])
      s.add_runtime_dependency(%q<money>.freeze, ["~> 6.9.0"])
      s.add_runtime_dependency(%q<representable>.freeze, ["~> 3.0.4"])
      s.add_runtime_dependency(%q<virtus>.freeze, ["~> 1.0.5"])
      s.add_development_dependency(%q<dotenv>.freeze, ["~> 2.2.1"])
      s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_development_dependency(%q<rainbow>.freeze, ["~> 2.2.2"])
      s.add_development_dependency(%q<rubocop>.freeze, ["~> 0.48.1"])
      s.add_development_dependency(%q<yard>.freeze, ["~> 0.9.9"])
      s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.14.1"])
      s.add_development_dependency(%q<capybara>.freeze, ["~> 2.14.0"])
      s.add_development_dependency(%q<cucumber>.freeze, ["~> 2.4.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.6.0"])
      s.add_development_dependency(%q<jsonpath>.freeze, ["~> 0.5.8"])
      s.add_development_dependency(%q<vcr>.freeze, ["~> 3.0.3"])
      s.add_development_dependency(%q<webmock>.freeze, ["~> 3.0.1"])
    else
      s.add_dependency(%q<activesupport>.freeze, ["~> 5.0"])
      s.add_dependency(%q<faraday>.freeze, ["~> 0.9.2"])
      s.add_dependency(%q<json>.freeze, ["~> 2.1.0"])
      s.add_dependency(%q<money>.freeze, ["~> 6.9.0"])
      s.add_dependency(%q<representable>.freeze, ["~> 3.0.4"])
      s.add_dependency(%q<virtus>.freeze, ["~> 1.0.5"])
      s.add_dependency(%q<dotenv>.freeze, ["~> 2.2.1"])
      s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_dependency(%q<rainbow>.freeze, ["~> 2.2.2"])
      s.add_dependency(%q<rubocop>.freeze, ["~> 0.48.1"])
      s.add_dependency(%q<yard>.freeze, ["~> 0.9.9"])
      s.add_dependency(%q<simplecov>.freeze, ["~> 0.14.1"])
      s.add_dependency(%q<capybara>.freeze, ["~> 2.14.0"])
      s.add_dependency(%q<cucumber>.freeze, ["~> 2.4.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.6.0"])
      s.add_dependency(%q<jsonpath>.freeze, ["~> 0.5.8"])
      s.add_dependency(%q<vcr>.freeze, ["~> 3.0.3"])
      s.add_dependency(%q<webmock>.freeze, ["~> 3.0.1"])
    end
  else
    s.add_dependency(%q<activesupport>.freeze, ["~> 5.0"])
    s.add_dependency(%q<faraday>.freeze, ["~> 0.9.2"])
    s.add_dependency(%q<json>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<money>.freeze, ["~> 6.9.0"])
    s.add_dependency(%q<representable>.freeze, ["~> 3.0.4"])
    s.add_dependency(%q<virtus>.freeze, ["~> 1.0.5"])
    s.add_dependency(%q<dotenv>.freeze, ["~> 2.2.1"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<rainbow>.freeze, ["~> 2.2.2"])
    s.add_dependency(%q<rubocop>.freeze, ["~> 0.48.1"])
    s.add_dependency(%q<yard>.freeze, ["~> 0.9.9"])
    s.add_dependency(%q<simplecov>.freeze, ["~> 0.14.1"])
    s.add_dependency(%q<capybara>.freeze, ["~> 2.14.0"])
    s.add_dependency(%q<cucumber>.freeze, ["~> 2.4.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.6.0"])
    s.add_dependency(%q<jsonpath>.freeze, ["~> 0.5.8"])
    s.add_dependency(%q<vcr>.freeze, ["~> 3.0.3"])
    s.add_dependency(%q<webmock>.freeze, ["~> 3.0.1"])
  end
end

