# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: expedia 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "expedia".freeze
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Alistair A. Israel".freeze]
  s.date = "2017-09-14"
  s.description = "Expedia Quick Connect API gem".freeze
  s.email = "aisrael@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".gitlab-ci.yml",
    ".rspec",
    ".rubocop.yml",
    ".ruby-gemset",
    ".ruby-version",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "features/expedia.feature",
    "features/step_definitions/expedia_steps.rb",
    "features/support/env.rb",
    "lib/expedia.rb",
    "lib/expedia/api.rb",
    "lib/expedia/api/client.rb",
    "lib/expedia/property.rb",
    "lib/expedia/rate_plan.rb",
    "lib/expedia/rate_threshold.rb",
    "lib/expedia/resource.rb",
    "lib/expedia/room_type.rb",
    "spec/client_spec.rb",
    "spec/property_spec.rb",
    "spec/room_type_spec.rb",
    "spec/spec_helper.rb",
    "test.rb",
    "vcr/rspec/Expedia_API_Client/fetch_property/should_retrieve_the_property_with_the_given_id.yml",
    "vcr/rspec/Expedia_API_Client/fetch_rate_plan/should_retrieve_the_rate_plan_with_the_given_id.yml",
    "vcr/rspec/Expedia_API_Client/fetch_rate_threshold/should_fetch_the_room_rate_threshold.yml",
    "vcr/rspec/Expedia_API_Client/fetch_room_type/should_retrieve_the_room_type_with_the_given_id.yml",
    "vcr/rspec/Expedia_API_Client/list_properties/should_retrieve_the_properties.yml",
    "vcr/rspec/Expedia_API_Client/list_room_types/should_retrieve_the_room_types_for_the_given_property_id.yml"
  ]
  s.homepage = "http://github.com/aisrael/expedia".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.12".freeze
  s.summary = "Expedia API".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>.freeze, ["~> 5.0"])
      s.add_runtime_dependency(%q<faraday>.freeze, ["~> 0.9.2"])
      s.add_runtime_dependency(%q<json>.freeze, ["~> 2.1.0"])
      s.add_runtime_dependency(%q<money>.freeze, ["~> 6.9.0"])
      s.add_runtime_dependency(%q<representable>.freeze, ["~> 3.0.4"])
      s.add_runtime_dependency(%q<virtus>.freeze, ["~> 1.0.5"])
      s.add_development_dependency(%q<dotenv>.freeze, ["~> 2.2.1"])
      s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_development_dependency(%q<rainbow>.freeze, ["~> 2.2.2"])
      s.add_development_dependency(%q<rubocop>.freeze, ["~> 0.48.1"])
      s.add_development_dependency(%q<yard>.freeze, ["~> 0.9.9"])
      s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.14.1"])
      s.add_development_dependency(%q<capybara>.freeze, ["~> 2.14.0"])
      s.add_development_dependency(%q<cucumber>.freeze, ["~> 2.4.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.6.0"])
      s.add_development_dependency(%q<jsonpath>.freeze, ["~> 0.5.8"])
      s.add_development_dependency(%q<vcr>.freeze, ["~> 3.0.3"])
      s.add_development_dependency(%q<webmock>.freeze, ["~> 3.0.1"])
    else
      s.add_dependency(%q<activesupport>.freeze, ["~> 5.0"])
      s.add_dependency(%q<faraday>.freeze, ["~> 0.9.2"])
      s.add_dependency(%q<json>.freeze, ["~> 2.1.0"])
      s.add_dependency(%q<money>.freeze, ["~> 6.9.0"])
      s.add_dependency(%q<representable>.freeze, ["~> 3.0.4"])
      s.add_dependency(%q<virtus>.freeze, ["~> 1.0.5"])
      s.add_dependency(%q<dotenv>.freeze, ["~> 2.2.1"])
      s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_dependency(%q<rainbow>.freeze, ["~> 2.2.2"])
      s.add_dependency(%q<rubocop>.freeze, ["~> 0.48.1"])
      s.add_dependency(%q<yard>.freeze, ["~> 0.9.9"])
      s.add_dependency(%q<simplecov>.freeze, ["~> 0.14.1"])
      s.add_dependency(%q<capybara>.freeze, ["~> 2.14.0"])
      s.add_dependency(%q<cucumber>.freeze, ["~> 2.4.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.6.0"])
      s.add_dependency(%q<jsonpath>.freeze, ["~> 0.5.8"])
      s.add_dependency(%q<vcr>.freeze, ["~> 3.0.3"])
      s.add_dependency(%q<webmock>.freeze, ["~> 3.0.1"])
    end
  else
    s.add_dependency(%q<activesupport>.freeze, ["~> 5.0"])
    s.add_dependency(%q<faraday>.freeze, ["~> 0.9.2"])
    s.add_dependency(%q<json>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<money>.freeze, ["~> 6.9.0"])
    s.add_dependency(%q<representable>.freeze, ["~> 3.0.4"])
    s.add_dependency(%q<virtus>.freeze, ["~> 1.0.5"])
    s.add_dependency(%q<dotenv>.freeze, ["~> 2.2.1"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<rainbow>.freeze, ["~> 2.2.2"])
    s.add_dependency(%q<rubocop>.freeze, ["~> 0.48.1"])
    s.add_dependency(%q<yard>.freeze, ["~> 0.9.9"])
    s.add_dependency(%q<simplecov>.freeze, ["~> 0.14.1"])
    s.add_dependency(%q<capybara>.freeze, ["~> 2.14.0"])
    s.add_dependency(%q<cucumber>.freeze, ["~> 2.4.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.6.0"])
    s.add_dependency(%q<jsonpath>.freeze, ["~> 0.5.8"])
    s.add_dependency(%q<vcr>.freeze, ["~> 3.0.3"])
    s.add_dependency(%q<webmock>.freeze, ["~> 3.0.1"])
  end
end

